- src: https://unpkg.com/@webcomponents/custom-elements@1.4.2/custom-elements.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  noModule: true
  defer: true
  integrity: sha384-xyhN4T4+9VPh8uXl6uWjGzsqwNXN9C2tla8b6zSrSqYlMFUoeCdoxiEJU0js+GNE
- src: https://unpkg.com/@shgysk8zer0/polyfills@0.3.0/all.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  integrity: sha384-h2kgNESJV1KN7BmHtXZv1j5WMcwFojESsbaNydwul3t6bqHOmzVMDaDXAEe6XLC+
  defer: true
- src: https://unpkg.com/@shgysk8zer0/kazoo@0.3.1/harden.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  integrity: sha384-55L/wO9o0uIVTeubRIDQB4bewfNqyxrj4OXuxlW24NMEk+ioZwMHVw/tFV78mM+k
  defer: true
- src: /js/index.min.js
  referrerPolicy: no-referrer
  defer: true
